# Generated by Django 5.0.2 on 2024-02-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(default=-2022, max_length=15),
            preserve_default=False,
        ),
    ]
