# Generated by Django 5.0.2 on 2024-02-10 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Фотография')),
                ('heading', models.CharField(max_length=50, verbose_name='Заголовок ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена ')),
                ('status', models.CharField(choices=[('модерация', 'На модерацию'), ('опубликовано', 'Опубликовано'), ('отклонено', 'Отклонено'), ('удаление', 'На удаление')], default='модерация', max_length=50, verbose_name='Статус')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата-время создания')),
                ('date_publications', models.DateTimeField(blank=True, null=True, verbose_name='Дата-время публикации')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата-время редактирования')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement', to=settings.AUTH_USER_MODEL, verbose_name='Автор ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.category', verbose_name='Категория ')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст ')),
                ('date_creation_com', models.DateTimeField(auto_now_add=True, verbose_name='Дата-время создания')),
                ('announcement_com', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.announcement', verbose_name='Объявление ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commet', to=settings.AUTH_USER_MODEL, verbose_name='Автор ')),
            ],
        ),
    ]
