# Generated by Django 5.0.2 on 2024-02-10 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/', verbose_name='Фотография'),
        ),
    ]
