# Generated by Django 5.0.2 on 2024-02-10 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_announcement_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='announcement_com',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='webapp.announcement', verbose_name='Объявление '),
        ),
    ]
